# Generated by Django 4.2.1 on 2023-06-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_expert_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='wallet',
            field=models.IntegerField(null=True),
        ),
    ]
