# Generated by Django 4.2.1 on 2023-06-06 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_name', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_tutorial_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.domain')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.tutorial')),
            ],
        ),
    ]
