# Generated by Django 4.2.1 on 2023-06-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='image',
            field=models.ImageField(default='upload_photo', upload_to='domain/image'),
        ),
    ]
