# Generated by Django 4.2.1 on 2023-06-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_domain_bloked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='bloked',
            new_name='blocked',
        ),
    ]
