# Generated by Django 4.2.1 on 2023-06-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
