# Generated by Django 4.2.1 on 2023-06-23 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_client_wallet'),
        ('order', '0004_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.client'),
        ),
    ]
