# Generated by Django 4.2.1 on 2023-06-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_slot_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
