# Generated by Django 4.2.1 on 2023-07-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_slot_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='number_of_person',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
