# Generated by Django 4.2.1 on 2023-07-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rating_number_of_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='count',
            field=models.IntegerField(default=5),
        ),
    ]
